# Generated by Django 5.0 on 2024-11-25 18:20

import clubes.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('parametros', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_pago', models.DateField()),
                ('modalidad_pago', models.CharField(choices=[('efectivo', 'Efectivo'), ('transferencia', 'Transferencia'), ('otros', 'Otros')], max_length=20)),
                ('monto_pagado', models.CharField(max_length=20)),
                ('cuotas_canceladas', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Pago',
                'verbose_name_plural': 'Pagos',
                'ordering': ['fecha_pago'],
            },
        ),
        migrations.CreateModel(
            name='Cuota',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2)),
                ('anio', models.CharField(max_length=4, verbose_name='año')),
                ('fecha_vencimiento', models.DateField(blank=True, null=True)),
                ('monto_base', models.DecimalField(decimal_places=2, help_text='Ingrese un valor mayor a 0', max_digits=9, validators=[clubes.validators.validate_valor_negativo])),
                ('monto_neto', models.DecimalField(decimal_places=2, help_text='Ingrese un valor mayor a 0', max_digits=9, validators=[clubes.validators.validate_valor_negativo])),
                ('pagada', models.BooleanField()),
                ('disciplina', models.ForeignKey(blank=True, help_text='Seleccionar disciplina sólo en caso de crear cuota deportiva', null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina')),
                ('socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
                ('tipo_socio', models.ForeignKey(blank=True, help_text='Seleccionar tipo de socio sólo en caso de crear cuota social, debe coincidir con el del Socio elegido', null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.tiposocio')),
            ],
            options={
                'verbose_name': 'Cuota',
                'verbose_name_plural': 'Cuotas',
                'ordering': ['mes', 'anio'],
            },
        ),
        migrations.CreateModel(
            name='EsquemaCuotaDeportiva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField(help_text='Ingrese un valor mayor a 0', validators=[clubes.validators.validate_valor_negativo])),
                ('dias_vencimiento', models.IntegerField(blank=True, null=True, validators=[clubes.validators.validate_valor_negativo])),
                ('cobra_mora', models.BooleanField(blank=True, default=False, null=True)),
                ('monto_penalizacion', models.IntegerField(blank=True, help_text='Porcentaje, ingrese un valor entre 0 y 100', null=True, validators=[clubes.validators.validate_valor_desde_hasta])),
                ('descuento_x_2', models.IntegerField(help_text='Ingrese un valor entre 0 y 100', validators=[clubes.validators.validate_valor_desde_hasta])),
                ('descuento_x_3', models.IntegerField(help_text='Ingrese un valor entre 0 y 100', validators=[clubes.validators.validate_valor_desde_hasta])),
                ('descuento_x_4', models.IntegerField(help_text='Ingrese un valor entre 0 y 100', validators=[clubes.validators.validate_valor_desde_hasta])),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.categoria')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina')),
            ],
            options={
                'verbose_name': 'Cuota Deportiva',
                'verbose_name_plural': 'Cuotas Deportivas',
                'ordering': ['monto'],
            },
        ),
        migrations.CreateModel(
            name='EsquemaCuotaSocial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dias_vencimiento', models.IntegerField(blank=True, null=True, validators=[clubes.validators.validate_valor_negativo])),
                ('cobra_mora', models.BooleanField(blank=True, default=False, null=True)),
                ('monto_penalizacion', models.IntegerField(blank=True, help_text='Porcentaje, ingrese un valor entre 0 y 100', null=True, validators=[clubes.validators.validate_valor_desde_hasta])),
                ('monto', models.FloatField(help_text='Ingrese un valor mayor a 0', validators=[clubes.validators.validate_valor_negativo])),
                ('descuento_x_2', models.IntegerField(help_text='Ingrese un valor entre 0 y 100', validators=[clubes.validators.validate_valor_desde_hasta])),
                ('descuento_x_3', models.IntegerField(help_text='Ingrese un valor entre 0 y 100', validators=[clubes.validators.validate_valor_desde_hasta])),
                ('descuento_x_4', models.IntegerField(help_text='Ingrese un valor entre 0 y 100', validators=[clubes.validators.validate_valor_desde_hasta])),
                ('tipo_socio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.tiposocio')),
            ],
            options={
                'verbose_name': 'Cuota Social',
                'verbose_name_plural': 'Cuotas Sociales',
                'ordering': ['monto'],
            },
        ),
    ]
