# Generated by Django 5.0 on 2024-12-09 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0002_alter_pago_options_rename_fecha_pago_pago_fecha_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pago',
            name='detalles',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='pago',
            name='referencia',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
