# Generated by Django 5.0 on 2024-12-11 01:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cuotas', '0004_alter_pago_options_cuota_pago'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuota',
            name='anio',
            field=models.CharField(max_length=4, verbose_name='Año'),
        ),
        migrations.AlterField(
            model_name='cuota',
            name='mes',
            field=models.CharField(choices=[('01', 'Enero'), ('02', 'Febrero'), ('03', 'Marzo'), ('04', 'Abril'), ('05', 'Mayo'), ('06', 'Junio'), ('07', 'Julio'), ('08', 'Agosto'), ('09', 'Septiembre'), ('10', 'Octubre'), ('11', 'Noviembre'), ('12', 'Diciembre')], max_length=2, verbose_name='Mes'),
        ),
    ]
