# Generated by Django 5.0 on 2024-11-25 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0001_initial'),
        ('disciplinas', '0001_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=150)),
                ('fecha_inicio', models.DateField()),
                ('fecha_fin', models.DateField(blank=True, null=True)),
                ('lugar', models.CharField(max_length=200)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
                ('categorias', models.ManyToManyField(blank=True, to='disciplinas.categoria')),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.ciudad')),
                ('disciplinas', models.ManyToManyField(blank=True, to='disciplinas.disciplina')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.estado')),
                ('institucion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.institucion')),
                ('tipo_evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.tipoevento')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['tipo_evento', 'nombre'],
            },
        ),
        migrations.CreateModel(
            name='ParticipantesEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=200, null=True)),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='eventos.evento')),
            ],
            options={
                'verbose_name': 'Participante de evento',
                'verbose_name_plural': 'Participantes de evento',
                'ordering': ['evento'],
            },
        ),
        migrations.CreateModel(
            name='ResponsableDeportivoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.categoria')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_deportivo', to='eventos.evento')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='responsable_deportivo_evento', to='club.personal')),
            ],
            options={
                'verbose_name': 'Responsable Deportivo del Evento',
                'verbose_name_plural': 'Responsables Deportivos del Evento',
            },
        ),
        migrations.CreateModel(
            name='ResponsableEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_personal', to='eventos.evento')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='evento_responsable_personal', to='club.personal')),
            ],
            options={
                'verbose_name': 'Responsable del Evento',
                'verbose_name_plural': 'Responsables del Evento',
            },
        ),
    ]
