# Generated by Django 5.0 on 2024-11-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='participantesevento',
            options={'ordering': ['evento'], 'verbose_name': 'Participante', 'verbose_name_plural': 'Participantes'},
        ),
        migrations.AlterModelOptions(
            name='responsabledeportivoevento',
            options={'verbose_name': 'Responsable Deportivo', 'verbose_name_plural': 'Responsables Deportivos'},
        ),
        migrations.AlterModelOptions(
            name='responsableevento',
            options={'verbose_name': 'Responsable Institucional', 'verbose_name_plural': 'Responsables Institucionales'},
        ),
    ]
