# Generated by Django 5.0 on 2024-12-11 01:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_grupo_telegram'),
        ('eventos', '0004_alter_evento_ciudad_alter_evento_estado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
            preserve_default=False,
        ),
    ]
