# Generated by Django 5.0 on 2024-12-19 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='alergia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='ciudad',
            name='codigo_postal',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='enfermedadinfancia',
            name='descripcion',
            field=models.TextField(blank=True, null=True),
        ),
    ]
