# Generated by Django 5.0 on 2024-12-20 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_delete_profesordisciplina'),
        ('parametros', '0002_alergia_descripcion_ciudad_codigo_postal_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='estado',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
            preserve_default=False,
        ),
    ]
