# Generated by Django 5.0 on 2024-11-25 18:18

import clubes.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Club',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('razon_social', models.CharField(max_length=255, unique=True)),
                ('CUIT', models.CharField(max_length=11, unique=True, validators=[clubes.validators.validar_cuit])),
                ('direccion', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.ciudad')),
            ],
            options={
                'verbose_name': 'Club',
                'verbose_name_plural': 'Clubes',
                'ordering': ['razon_social'],
            },
        ),
        migrations.CreateModel(
            name='DocumentoVinculado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('detalle', models.TextField(blank=True, null=True)),
                ('archivo', models.FileField(upload_to='upload/')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.tipoarchivo')),
            ],
            options={
                'verbose_name': 'Documento Vinculado',
                'verbose_name_plural': 'Documentos Vinculados',
                'ordering': ['tipo_documento'],
            },
        ),
        migrations.CreateModel(
            name='Personal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('fecha_nacimiento', models.DateField()),
                ('nro_documento', models.CharField(max_length=20, unique=True)),
                ('CUIL', models.CharField(max_length=11, unique=True, validators=[clubes.validators.validar_cuit])),
                ('direccion', models.CharField(max_length=100)),
                ('nro_telefono', models.CharField(max_length=30)),
                ('email', models.EmailField(max_length=255, unique=True)),
                ('estado', models.BooleanField(verbose_name='Activo')),
                ('fecha_ingreso', models.DateField()),
                ('fecha_egreso', models.DateField(blank=True, null=True)),
                ('descripcion_tareas', models.TextField(blank=True, null=True)),
                ('ciudad', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.ciudad')),
                ('club', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club')),
                ('genero', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.genero')),
                ('tipo_documento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.tipodocumento')),
                ('tipo_personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.tipopersonal')),
            ],
            options={
                'verbose_name': 'Personal',
                'verbose_name_plural': 'Personal',
                'ordering': ['nombre'],
            },
        ),
        migrations.CreateModel(
            name='ProfesorDisciplina',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('disciplina', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina')),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.personal')),
            ],
            options={
                'verbose_name': 'Profesor Disciplina',
                'verbose_name_plural': 'Profesor Disciplina',
            },
        ),
    ]
