# Generated by Django 5.0 on 2024-11-26 18:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='documentovinculado',
            options={'ordering': ['tipo_documento'], 'verbose_name': 'Documento', 'verbose_name_plural': 'Documentos'},
        ),
    ]
