# Generated by Django 5.0 on 2024-11-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0002_alter_documentovinculado_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='grupo_telegram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
