# Generated by Django 5.0 on 2024-12-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_grupo_telegram'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProfesorDisciplina',
        ),
    ]
