# Generated by Django 5.0 on 2025-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0004_delete_profesordisciplina'),
    ]

    operations = [
        migrations.AddField(
            model_name='club',
            name='secuencia_socio',
            field=models.IntegerField(default=0),
        ),
    ]
