# Generated by Django 5.0 on 2024-12-02 11:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('club', '0003_club_grupo_telegram'),
        ('disciplinas', '0003_categoria_grupo_telegram_disciplina_grupo_telegram'),
        ('socios', '0003_socio_grupo_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoArticulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('imagen', models.ImageField(upload_to='')),
            ],
            options={
                'verbose_name_plural': 'Tipos de Artículos',
            },
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('stock', models.IntegerField(default=0)),
                ('imagen', models.ImageField(upload_to='')),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina')),
                ('tipoArticulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='indumentaria.tipoarticulo')),
            ],
            options={
                'verbose_name_plural': 'Artículos',
            },
        ),
        migrations.CreateModel(
            name='Entrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(verbose_name='Fecha de Entrega')),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Procesada')], default='P', max_length=1)),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_alm_per', to='club.personal')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='fk_alm_soc', to='socios.socio')),
            ],
            options={
                'verbose_name_plural': 'Entregas de Artículos',
            },
        ),
        migrations.CreateModel(
            name='DetalleEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_det_ent_art', to='indumentaria.articulo')),
                ('entrega', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_det_ent', to='indumentaria.entrega')),
            ],
            options={
                'verbose_name_plural': 'Detalle de Entregas de Artículos',
            },
        ),
        migrations.CreateModel(
            name='Recepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('referencia', models.CharField(blank=True, max_length=100, null=True)),
                ('estado', models.CharField(choices=[('P', 'Pendiente'), ('C', 'Procesada')], default='P', max_length=1, verbose_name='Estado')),
                ('personal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_rec_alm_per', to='club.personal')),
            ],
            options={
                'verbose_name_plural': 'Recepcion de Artículos',
            },
        ),
        migrations.CreateModel(
            name='DetalleRecepcion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('articulo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_det_rec_art', to='indumentaria.articulo')),
                ('recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fk_det_rec', to='indumentaria.recepcion')),
            ],
            options={
                'verbose_name_plural': 'Detalle de Recepcion de Artículos',
            },
        ),
    ]
