# Generated by Django 5.0 on 2024-12-02 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indumentaria', '0002_articulo_club_detalleentrega_club_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='destacado',
            field=models.BooleanField(default=False),
        ),
    ]
