# Generated by Django 5.0 on 2024-12-02 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('indumentaria', '0003_articulo_destacado'),
    ]

    operations = [
        migrations.AddField(
            model_name='articulo',
            name='costo',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='articulo',
            name='precio',
            field=models.FloatField(default=0),
        ),
    ]
