# Generated by Django 5.0 on 2024-11-25 18:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('disciplinas', '0001_initial'),
        ('parametros', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervencion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referentes', models.CharField(blank=True, max_length=200, null=True)),
                ('fecha', models.DateField()),
                ('notas', models.CharField(max_length=250)),
                ('disciplina', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina')),
                ('estado', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.estado')),
                ('socio', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='socios.socio')),
                ('tipo_intervencion', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.tipointervencion')),
            ],
            options={
                'verbose_name': 'Intervención',
                'verbose_name_plural': 'Intervenciones',
                'ordering': ['tipo_intervencion'],
            },
        ),
    ]
