# Generated by Django 5.0 on 2024-12-10 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_grupo_telegram'),
        ('intervenciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='intervencion',
            name='notas',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='referentes',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.personal'),
        ),
    ]
