# Generated by Django 5.0 on 2024-12-11 01:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_grupo_telegram'),
        ('disciplinas', '0007_remove_disciplina_grupo_telegram'),
        ('intervenciones', '0002_alter_intervencion_notas_and_more'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='intervencion',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='estado',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='parametros.estado', verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='fecha',
            field=models.DateField(verbose_name='Fecha'),
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='notas',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.RemoveField(
            model_name='intervencion',
            name='referentes',
        ),
        migrations.AlterField(
            model_name='intervencion',
            name='tipo_intervencion',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='parametros.tipointervencion'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='intervencion',
            name='referentes',
            field=models.ManyToManyField(to='club.personal'),
        ),
    ]
