# Generated by Django 5.0 on 2024-11-25 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0001_initial'),
        ('disciplinas', '0001_initial'),
        ('socios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
        ),
        migrations.AddField(
            model_name='profesorcategoria',
            name='profesor',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='Profesor', to='club.personal'),
        ),
        migrations.AddField(
            model_name='sociocategoria',
            name='socio',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='socio', to='socios.socio'),
        ),
    ]
