# Generated by Django 5.0 on 2024-11-27 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0002_disciplina_club_profesorcategoria_profesor_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='grupo_telegram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='grupo_telegram',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
