# Generated by Django 5.0 on 2024-12-02 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0003_categoria_grupo_telegram_disciplina_grupo_telegram'),
        ('socios', '0003_socio_grupo_telegram'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociocategoria',
            options={},
        ),
        migrations.AlterUniqueTogether(
            name='sociocategoria',
            unique_together={('socio', 'categoria')},
        ),
    ]
