# Generated by Django 5.0 on 2024-12-03 01:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0004_alter_sociocategoria_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociocategoria',
            options={'verbose_name': 'Socio Categoria', 'verbose_name_plural': 'Socios Categoria'},
        ),
    ]
