# Generated by Django 5.0 on 2024-12-05 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0005_alter_sociocategoria_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='color',
            field=models.CharField(choices=[('#288313', 'Verde'), ('#ff5733', 'Naranja'), ('#67e1e3', 'Celeste'), ('#f23727', 'Rojo'), ('#000000', 'Negro'), ('#e8ea39', 'Amarillo'), ('#d83fd4', 'Violeta')], default='#288313', max_length=7),
        ),
    ]
