# Generated by Django 5.0 on 2024-12-11 14:01
# Generated by Django 5.0 on 2024-12-09 20:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0006_disciplina_color'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='disciplina',
            name='grupo_telegram',
        ),
    ]
