# Generated by Django 5.0 on 2024-12-11 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_grupo_telegram'),
        ('disciplinas', '0007_remove_disciplina_grupo_telegram'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='club',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='club',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='club.club'),
        ),
    ]
