# Generated by Django 5.0 on 2024-12-13 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0008_categoria_club_alter_disciplina_club'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='imagen',
            field=models.ImageField(default='logo.png', upload_to=''),
        ),
    ]
