# Generated by Django 5.0 on 2024-12-16 15:27

import ckeditor_uploader.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0010_horario_club_profesorcategoria_club_and_more'),
        ('parametros', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='info',
            field=ckeditor_uploader.fields.RichTextUploadingField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='horario',
            name='cancha',
            field=models.ForeignKey(limit_choices_to={'apto_deporte': True}, on_delete=django.db.models.deletion.CASCADE, to='parametros.espacio', verbose_name='Espacio'),
        ),
    ]
