# Generated by Django 5.0 on 2024-12-16 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0011_disciplina_info_alter_horario_cancha'),
    ]

    operations = [
        migrations.AddField(
            model_name='disciplina',
            name='imagenContenido1',
            field=models.ImageField(default='logo.png', upload_to='', verbose_name='Imagen de contenido 1'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='imagenContenido2',
            field=models.ImageField(default='logo.png', upload_to='', verbose_name='Imagen de contenido 2'),
        ),
        migrations.AddField(
            model_name='disciplina',
            name='imagenContenido3',
            field=models.ImageField(default='logo.png', upload_to='', verbose_name='Imagen de contenido 3'),
        ),
        migrations.AlterField(
            model_name='disciplina',
            name='imagen',
            field=models.ImageField(default='logo.png', upload_to='', verbose_name='Ícono'),
        ),
    ]
