# Generated by Django 5.0 on 2025-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0012_disciplina_imagencontenido1_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='anio',
            field=models.IntegerField(default=2025, verbose_name='Año'),
        ),
    ]
