# Generated by Django 5.0 on 2024-12-03 22:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0003_socio_grupo_telegram'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='email_contacto_escolar',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='email_responsable',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
    ]
