# Generated by Django 5.0 on 2024-12-19 10:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('parametros', '0002_alergia_descripcion_ciudad_codigo_postal_and_more'),
        ('socios', '0004_alter_socio_email_contacto_escolar_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='alergias',
            field=models.ManyToManyField(blank=True, null=True, to='parametros.alergia'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='dificultades',
            field=models.ManyToManyField(blank=True, null=True, to='parametros.dificultad'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='fecha_ingreso',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socio',
            name='medicaciones',
            field=models.ManyToManyField(blank=True, null=True, to='parametros.medicacion'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='tipo_socio',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='parametros.tiposocio'),
        ),
        migrations.AlterField(
            model_name='socio',
            name='vacunas',
            field=models.ManyToManyField(blank=True, null=True, to='parametros.vacuna'),
        ),
    ]
