# Generated by Django 5.0 on 2025-01-16 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0005_alter_socio_alergias_alter_socio_dificultades_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='nro_socio',
            field=models.IntegerField(blank=True, default=0, null=True, unique=True),
        ),
    ]
