# Generated by Django 5.0 on 2025-01-17 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0006_socio_nro_socio'),
    ]

    operations = [
        migrations.AddField(
            model_name='socio',
            name='nro_inscripcion',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
