# Generated by Django 5.0 on 2025-01-17 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('socios', '0007_socio_nro_inscripcion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socio',
            name='nro_socio',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
