# Generated by Django 5.0 on 2024-12-11 02:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('club', '0003_club_grupo_telegram'),
        ('movimientos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='egreso',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='ingreso',
            name='club',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='club.club'),
            preserve_default=False,
        ),
    ]
