# Generated by Django 5.0 on 2024-12-03 01:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('disciplinas', '0005_alter_sociocategoria_options'),
        ('notificaciones', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mensaje',
            name='categoria',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplinas.categoria', verbose_name='Categoria'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='disciplina',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='disciplinas.disciplina', verbose_name='Disciplina'),
        ),
        migrations.AlterField(
            model_name='mensaje',
            name='estado',
            field=models.CharField(choices=[('P', 'Pendiente'), ('E', 'Enviado'), ('C', 'Cancelado')], default='P', max_length=1, verbose_name='Estado'),
        ),
    ]
